services:

    # Contao frontend module Comfortmedia\ContaoPraxisOpeningHours\Controller\FrontendModule\OpeningHoursListingModulesController
    # We used annotations for tagging the frontend module category, the frontend module type and the frontend module template
    Comfortmedia\ContaoPraxisOpeningHours\Controller\FrontendModule\OpeningHoursListingModulesController:
        tags:
            - { name: container.service_subscriber }
        public: true
        # Since Symfony 5 the container has to be set manually
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
    
    # Contao content element Comfortmedia\ContaoPraxisOpeningHours\Controller\ContentElement\HeroimageElementController
    # We used annotations for tagging the frontend element category, the frontend element type and the frontend element template
    Comfortmedia\ContaoPraxisOpeningHours\Controller\ContentElement\HeroimageElementController:
        tags:
            - { name: container.service_subscriber }
        public: true
        # Since Symfony 5 the container has to be set manually
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]

